
- hosts: all
  gather_facts: true

  vars:
    kolla_container_engine: docker
    container_registry_host: "192.168.10.165"

  handlers:
  - name: restart_docker
    systemd:
      name: docker
      state: restarted

  tasks:
  - name: Install Required packages
    ansible.builtin.dnf:
      name:
      - python3-packaging
      - python3-pip
      state: latest
    when: ansible_os_family == "RedHat"

#  - name: Install Required pip modules
#    ansible.builtin.pip:
#      name:
#      - podman
#    when: kolla_container_engine == "podman"

  - name: Block to install docker packages
    block:
    - name: Install docker repo
      ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      changed_when: true
      when: ansible_os_family == "RedHat"

    - name: Install Docker packages
      ansible.builtin.dnf:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      when: ansible_os_family == "RedHat"

    - name: Install Required pip modules
      ansible.builtin.pip:
        name:
        - docker

    # - name: Set insecure-registries
    #   ansible.builtin.template:
    #     src: docker-daemon.json
    #     dest: /etc/docker/daemon.json
    #     mode: 0644
    #     owner: root
    #     group: root
    #   notify: restart_docker

    - name: Start docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
    when: kolla_container_engine == "docker"


